name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Get the version from package.json
      - name: Get version from package.json
        id: get_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      # 3. Extract the changelog for the current version
      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          VERSION="${{ env.version }}"
          echo "Looking for changelog for $VERSION"

          # Match '## [X.Y.Z]' even if there's a date after it
          RELEASE_NOTES=$(awk "/## \\[${VERSION}\\]/ {flag=1; next} /^## \\[/ && \$2 != \"[${VERSION}]\" {flag=0} flag" CHANGELOG.md)

          # Fallback if empty
          if [ -z "$RELEASE_NOTES" ]; then
            echo "No changelog entry found for $VERSION"
            RELEASE_NOTES="No detailed release notes available."
          fi

          echo "release_notes<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # 4. Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: "Release v${{ env.version }}"
          body: ${{ env.release_notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
